import React, { useState } from "react";
import Dock from "react-osx-dock";
import {motion} from "framer-motion";
import Image from "next/image";
import Head from "next/head";

export default function Home() {
  // var portfolio = false;
  const [p, setP] = useState("portfolio");
  const [show, setShow] = useState(true);
  const [large, setLarge]= useState(true)

 const d = new Date();
 const day = d.toLocaleString('en-US',{weekday:'short'});
 const date = d.getDate()
 const month = d.toLocaleString('en-US',{month:'short'});
 const time = d.toLocaleString('en-US',{hour:'numeric',minute:'numeric',hour12:true});

  return (
    <>
     <Head>
        <title>Devansh Khullar | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[url('/wallpaper.jpg')] h-screen w-screen bg-cover bg-no-repeat relative overflow-x-hidden ">
        <div className="bg-slate-300 bg-opacity-50 flex justify-between">
        <div>
        <Image src="/apple.png" alt="apple" width={4} height={4} className="w-4 h-4 ml-4 my-1"  />
        </div>
        <div className="font-medium mr-2 text-md flex " >
         <div>
         <Image src="/toggle.png" alt="toggle" width={4} height={4} className="h-4 w-4 mt-1 mr-3" /> 
         </div>
         <div>

           {day} {date} {month} {time}
         </div>
        </div>
        </div>

        {show && (
          <motion.div  drag
          dragConstraints={{
            top: 0,
            left: 0,
            right: 1000,
            bottom: 100,
          }} initial={{ opacity: 0 }}
          animate={{ opacity: 1,duration:1 }}
          exit={{ opacity: 0 }} className={`${large?"w-screen":"w-1/3"} bg-white border-1 rounded-t-xl`}>
            <div className="bg-white border-b-2 rounded-t-xl border-gray-300 flex " >
              <div className="rounded-full bg-red-500 h-3 w-3 mt-2 mb-1 ml-2" onClick={()=> {setShow(false)}} >

              </div>
              <div className="rounded-full bg-yellow-500 h-3 w-3 mt-2 mb-1 ml-1 " >
                
              </div>
              <div className="rounded-full bg-green-500 h-3 w-3 mt-2 mb-1 ml-1 " onClick={()=>{setLarge(!large)}} >
                
              </div>
              </div>
            <iframe
              src="https://www.devanshkhullar.xyz/"
              className={`${
                p === "portfolio" ? "block" : "hidden"
              } w-full ${large?"h-[83vh]":"h-[75vh]"}  `}
            />
            <iframe
              src="https://raktbank.xyz/"
              className={`${
                p === "raktbank" ? "block" : "hidden"
              } w-full ${large?"h-[83vh]":"h-[75vh]"}`}
            />
            <iframe
              src="https://moda-online-shopping.vercel.app/"
              className={`${
                p === "moda" ? "block" : "hidden"
              }  w-full ${large?"h-[83vh]":"h-[75vh]"}`}
            />
            <iframe
              src="https://video-chat-app-14.netlify.app/"
              className={`${
                p === "videochat" ? "block" : "hidden"
              }  w-full ${large?"h-[83vh]":"h-[75vh]"}`}
            />
            <iframe
              src="https://my-memories-app123.netlify.app/"
              className={`${
                p === "memories" ? "block" : "hidden"
              }  w-full ${large?"h-[83vh]":"h-[75vh]"}`}
            />
          </motion.div>
        )}

        <div className=" hidden md:block">
          <Dock
            className="z-0 absolute bottom-0 md:left-1/4 ml-24"
            backgroundClassName="bg-slate-300 bg-opacity-50 border-1 rounded-3xl"
            width={400}
            magnification={0.5}
            magnifyDirection="up"
          >
            {["moda", "raktbank", "portfolio", "memories", "videochat"].map(
              (item, index) => (
                <Dock.Item
                  className="cursor-pointer px-4 "
                  key={index}
                  onClick={()=>{ setP(item); setShow(true)}}
                >
                  <img src={`${item}.png`}/>
                </Dock.Item>
              )
            )}
          </Dock>
        </div>
        <div className=" block md:hidden ">
          <Dock
            className="z-0 absolute bottom-0 "
            backgroundClassName="bg-slate-300 bg-opacity-50 border-1 rounded-lg"
            width={250}
            magnification={1}
            magnifyDirection="up"
          >
            {["portfolio", "raktbank", "moda", "memories", "videochat"].map(
              (item, index) => (
                <Dock.Item
                  className="cursor-pointer px-2 "
                  key={index}
                  onClick={() => {setP(item); setShow(true)}}
                >
                  <img src={`${item}.png`} />
                </Dock.Item>
              )
            )}
          </Dock>
        </div>
      </div>
    </>
  );
};
